### ISSUE TITLE
soatok/patreon-php could not be found in any version

### ISSUE THREAD

**Issue by pifagor87** [soatok/patreon-php#4]
> composer require soatok/patreon-php:^0
or
> composer require soatok/patreon-php

The requested package soatok/patreon-php could not be found in any version, there may be a typo in the package name

**Comment by soatok** [comment]
https://packagist.org/packages/soatok/patreon

It's just `soatok/patreon`. I'll update the docs.

**Comment by soatok** [comment]
Fixed in https://github.com/soatok/patreon-php/commit/009a56344ace68b2cd807ad6260921c7e326a723

I'll release a new version as soon as I can. I'm busy with work stuff tonight.

**Comment by millette** [comment]
Fixed :-)
